#include <iostream>
#include <cmath>
#include <GL/glew.h> 
#include <GL/freeglut.h>
#include "gl3d.h"
#include "myglm.h"
#include "debug.h"
#include "mycontext.h"
#include "myglew.h"
#include "keyboard.h"
#include "reshape.h"
#include "light.h"
#include "mvp.h"
#include "myshader.h"
#include "ImageFile.h"
